name: ğŸŒ Python application

on:
  push:
    branches: [ "feature/slack-brachi" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: ğŸ¨ Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"

    - name: ğŸ—ƒï¸ Install dependencies for server test
      run: pip install -r requirements.txt

    - name: âœˆï¸ Run tests for server test
      working-directory: test
      run: pytest

    - name: âœï¸ Install Ruff
      run: pip install ruff

    - name: ğŸ“ Run Ruff Linter
      run: ruff check
